### ISSUE TITLE
Multiple paper types for PDF

### ISSUE THREAD

**Issue by sgjohnston** [opentorah/opentorah#109]
I'm working on converting an existing build from ant to gradle, and using your docbook plugin. The build needs to generate a PDF of the output, in addition to html, and the PDF needs to be formatted for both A4 and USLetter paper. It is this latter requirement that is proving tricky, because there is only one PDF section possible, and one paper.type configuration allowed.

I've hacked up something by creating an additional gradle task of type org.opentorah.docbook.plugin.ProcessDocBookTask. This works, but is not very clean - I need to provide default values for all of the parameters, as I'm bypassing the configuration extension doing this (where the defaults are set), and I'm also struggling to find a clean way to share all of the rest of the config I need between the different docbook tasks.

Really, my question is whether there is a better way, or if I'm missing the obvious, to allow two PDFs to be generated, using different paper sizes, in one build.

**Comment by dubinsky** [comment]
@sgjohnston this is a valid request, and unfortunately, you are not missing missing anything: this functionality is not currently available... but it should be.

It'll take some doing, so you'll have to live with the workaround you came up with for a while I am afraid. I'd like to hear your ideas about how such functionality should look: apply configuration to all tasks of class `ProcessDocBookTask` and allow overrides? Introduce named variant subsections (for the sections corresponding to the output formats)? Something else?

Thanks!

**Comment by sgjohnston** [comment]
@dubinsky thanks for considering.

I'm not completely comfortable with the approach of using multiple tasks, although I can see that perhaps this is the easiest way around the problem. In this case, applying the configuration from the configuration extension (and including the defaults that are currently applied when using the plugin task) to all tasks would go a long way to making it better. The reason I'm not totally sure about this approach is how the src/main/xsl files, etc, are written on each invocation of the task - they would be overwritten on the second task execution, and so what ends up there just depends on the task order, which doesn't seem great.

So I think the idea of named variant subsections is great - although probably a lot more complex :-) This would allow just one task to execute and all of the desired output to be generated. I guess the subsections could generate named files like pdf-a4-params.xsl, pdf-a4-custom.xsl, and so on?

In the meantime, I'll use the workaround I've got.

thanks...

**Comment by dubinsky** [comment]
@sgjohnston
I added support for `variants` (parameter sections with names like `pdf-a4`) in v0.7.51 of the plugin (`README.md` [diff](https://github.com/opentorah/opentorah/pull/110/files#diff-2c2af7f0cacd6fe9e683d4e2f8c1bfc7R25))

Does this work for you? Are there any tweaks that you think are in order? Any suggestions for better documentation?
Thanks!

**Comment by sgjohnston** [comment]
@dubinsky that is fantastic, it works really well. Thanks for doing this so quickly.

One possible tweak, not necessary but would be nice assuming no side effects: I like how the variant (eg pdf-a4) inherits parameters from the base (pdf). What about doing the same for pdf-custom.xsl, so that customised style sheet changes can be shared between variants? I guess just an include of pdf-custom.xsl in the variant xsl? Especially as the pdf-custom.xsl file is generated, even when variants are in use.

Cheers!

**Comment by dubinsky** [comment]
@sgjohnston That was the intent; I just messed up the implementation - and just patched it (same version: v0.7.51).

**Comment by sgjohnston** [comment]
Looks good!

**Comment by dubinsky** [comment]
Closing then. Thank you for your cooperation!
